In [79]:
import numpy as np

In [80]:
print("Enter the row & col of matrix 1")
dim1 = list(map(int, input().split()))
print("Enter the values separated by space") 
matrix1 = list(map(int, input().split()))
matrix1 = np.array(matrix1).reshape(dim1[0], dim1[1])
print(matrix1,type(matrix1))

print("Enter the row & col of matrix 2")
dim2 = list(map(int, input().split()))
print("Enter the values separated by space") 
matrix2 = list(map(int, input().split()))
matrix2 = np.array(matrix2).reshape(dim2[0], dim2[1])
print(matrix2,type(matrix2))

Enter the row & col of matrix 1
2 2
Enter the values separated by space
1 2 3 4
[[1 2]
 [3 4]] <class 'numpy.ndarray'>
Enter the row & col of matrix 2
2 2
Enter the values separated by space
4 3 2 1
[[4 3]
 [2 1]] <class 'numpy.ndarray'>


In [84]:
class matrixop:
  def __init__(self,matrix1,matrix2):
    self.matrix1 = matrix1
    self.matrix2 = matrix2


  def mat_multi(self):
    result = np.dot(self.matrix1,self.matrix2)
    print('result of matrix multi is: ')
    print(result)

  def mat_det(self,matrixnum):
    if matrixnum == 1:
      print('Determinant of matrix is:',np.linalg.det(self.matrix1))
    else:
      print('Determinant of matrix is:',np.linalg.det(self.matrix2))    
  
  def trans(self,matrixnum):
    if matrixnum == 1:
      print('Transpose of matrix is:')
      print(self.matrix1.transpose())
    else:
      print('Transpose of matrix is:')
      print(self.matrix2.transpose())
  
  def adj(self,matrixnum):
    '''
    adjoint of matrix is transpose of cofactor matrix of a given square matrix
    cofactor matrix is inverse of matrix * determinant of matrix
    '''
    if matrixnum == 1:
      cof_m = np.linalg.inv(self.matrix1).T * np.linalg.det(self.matrix1)
      adj = cof_m.transpose()
      print(adj)
    else:
      cof_m = np.linalg.inv(self.matrix2).T * np.linalg.det(self.matrix2)
      adj = cof_m.transpose()
      print(adj)
   
  def inv(self,matrixnum):
    if matrixnum == 1:
      print(np.linalg.inv(self.matrix1))
    else:
      print(np.linalg.inv(self.matrix2))

In [91]:
my_obj = matrixop(matrix1,matrix2)

while True:
  a = '''
      Press 1 for matrix multiplication
      Press 2 for matrix Determinant 
      Press 3 for matrix Transpose
      Press 4 for matrix Adjoint
      Press 5 for matrix Inverse
      Press 0 to Exit
      '''
  option = int(input(a))
  if option == 1:
    my_obj.mat_multi()

  elif option == 2:
    m_num = input('Enter matrix number')
    my_obj.mat_det(m_num)

  elif option == 3:
    m_num = input('Enter matrix number')
    my_obj.trans(m_num)

  elif option == 4:
    m_num = input('Enter matrix number')
    my_obj.adj(m_num)

  elif option == 5:
    m_num = input('Enter matrix number')
    my_obj.inv(m_num)

  elif option == 0:
    break


      Press 1 for matrix multiplication
      Press 2 for matrix Determinant 
      Press 3 for matrix Transpose
      Press 4 for matrix Adjoint
      Press 5 for matrix Inverse
      Press 0 to Exit
      1
result of matrix multi is: 
[[ 8  5]
 [20 13]]

      Press 1 for matrix multiplication
      Press 2 for matrix Determinant 
      Press 3 for matrix Transpose
      Press 4 for matrix Adjoint
      Press 5 for matrix Inverse
      Press 0 to Exit
      2
Enter matrix number1
Determinant of matrix is: -2.0

      Press 1 for matrix multiplication
      Press 2 for matrix Determinant 
      Press 3 for matrix Transpose
      Press 4 for matrix Adjoint
      Press 5 for matrix Inverse
      Press 0 to Exit
      3
Enter matrix number1
Transpose of matrix is:
[[4 2]
 [3 1]]

      Press 1 for matrix multiplication
      Press 2 for matrix Determinant 
      Press 3 for matrix Transpose
      Press 4 for matrix Adjoint
      Press 5 for matrix Inverse
      Press 0 to Exit
      4
E