In [30]:
import numpy as np
import pandas as pd
import tensorflow as tf

dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

print(X[1])

[608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]


In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [32]:
print(X[1])

[608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]


In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [34]:
print(X[1])

[0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]


In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 59)

In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [37]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [38]:
model.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
250/250 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7702
Epoch 2/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4584 - accuracy: 0.7937
Epoch 3/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4504 - accuracy: 0.7909
Epoch 4/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4321 - accuracy: 0.8011
Epoch 5/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4268 - accuracy: 0.7969
Epoch 6/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4259 - accuracy: 0.7998
Epoch 7/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4293 - accuracy: 0.7974
Epoch 8/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4159 - accuracy: 0.8061
Epoch 9/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4282 - accuracy: 0.8114
Epoch 10/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4319 - accuracy: 0.8078

In [39]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1521   76]
 [ 225  178]]


0.8495